### ISSUE TITLE
remark描述错误

### ISSUE THREAD

**Issue by hsn8086** [HCAT-Project/HCAT-Project-Docs#2]
remark为备注
![Screenshot_20230127_005816_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/51445446/214899577-8670b5af-e540-48b9-a256-f3cc8919419d.jpg)

**Comment by NatsumiXD** [comment]
哪个API条目?

**Comment by hsn8086** [comment]
group下所有涉及remark的(大概
