### ISSUE TITLE
部分接口重命名

### ISSUE THREAD

**Issue by hsn8086** [HCAT-Project/HCAT-Project-Docs#4]
get_group_admins->get_admins
get_group_members->get_members
get_group_name->get_name
get_group_owner->get_owner
get_group_setting->get_setting

**Comment by NatsumiXD** [comment]
fixed #4 but why don't rename "get_groups_list"

**Comment by hsn8086** [comment]
因为get_list不能体现拿的是什么列表
get_groups没有其他信息
